"""Add Section model

Revision ID: 583c5e6ef559
Revises: 0a783de843f2
Create Date: 2026-03-15 13:42:57.208579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583c5e6ef559'
down_revision: Union[str, Sequence[str], None] = '0a783de843f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.add_column('questions', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.add_column('test_results', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_results', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.drop_column('test_results', 'section_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'section_id')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###
