"""add_teacher_id_to_groups

Revision ID: 9e768d0d5df5
Revises: 9c1b1381d899
Create Date: 2026-03-30 16:34:55.342861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e768d0d5df5'
down_revision: Union[str, Sequence[str], None] = '9c1b1381d899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'teacher_id')
    # ### end Alembic commands ###
